In [22]:
import pandas as pd 
import numpy as np 
import requests

df = pd.read_json('../data/auto.json')

In [23]:
pd.options.display.float_format = '{:.2f}'.format
df

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

In [24]:
sample_df = df.sample(200, random_state=21)
concat_rows = pd.concat([df, sample_df])
concat_rows.index = range(len(concat_rows))
concat_rows

        CarNumber  Refund   Fines        Make   Model
0    Y163O8161RUS       2 3200.00        Ford   Focus
1     E432XX77RUS       1 6500.00      Toyota   Camry
2     7184TT36RUS       1 2100.00        Ford   Focus
3    X582HE161RUS       2 2000.00        Ford   Focus
4    92918M178RUS       1 5700.00        Ford   Focus
..            ...     ...     ...         ...     ...
920  8182XX154RUS       1  200.00        Ford   Focus
921   X796TH96RUS       1  500.00        Ford   Focus
922  T011MY163RUS       2 4000.00        Ford   Focus
923   T341CC96RUS       2 1000.00  Volkswagen  Passat
924   T119CT96RUS       1 2000.00        Ford   Focus

[925 rows x 5 columns]

In [25]:
len(concat_rows)

925

In [26]:
np.random.seed(21)
Year = np.random.randint(1980, 2019, len(concat_rows))
Year = pd.Series(Year, name='Year')
Year

0      1989
1      1995
2      1984
3      2015
4      2014
       ...
920    1996
921    2002
922    1996
923    2012
924    1984
Name: Year, Length: 925, dtype: int64

In [27]:
new_df = pd.concat([concat_rows, Year], axis=1)
new_df

        CarNumber  Refund   Fines        Make   Model  Year
0    Y163O8161RUS       2 3200.00        Ford   Focus  1989
1     E432XX77RUS       1 6500.00      Toyota   Camry  1995
2     7184TT36RUS       1 2100.00        Ford   Focus  1984
3    X582HE161RUS       2 2000.00        Ford   Focus  2015
4    92918M178RUS       1 5700.00        Ford   Focus  2014
..            ...     ...     ...         ...     ...   ...
920  8182XX154RUS       1  200.00        Ford   Focus  1996
921   X796TH96RUS       1  500.00        Ford   Focus  2002
922  T011MY163RUS       2 4000.00        Ford   Focus  1996
923   T341CC96RUS       2 1000.00  Volkswagen  Passat  2012
924   T119CT96RUS       1 2000.00        Ford   Focus  1984

[925 rows x 6 columns]

In [28]:
surname_df = pd.read_json('../data/surname.json')
surname_df.columns = surname_df.iloc[0]
surname = surname_df[1:]
surname = surname.reset_index(drop=True)
surname

0       NAME    COUNT RANK
0      ADAMS   427865   42
1      ALLEN   482607   33
2    ALVAREZ   233983   92
3   ANDERSON   784404   15
4     BAILEY   277845   72
..       ...      ...  ...
95  WILLIAMS  1625252    3
96    WILSON   801882   14
97      WOOD   250715   84
98    WRIGHT   458980   35
99     YOUNG   484447   32

[100 rows x 3 columns]

In [29]:
unique_car_nums = concat_rows['CarNumber'].unique()
np.random_state = 21
surnames = pd.Series(np.random.choice(surname['NAME'], size=len(unique_car_nums)))
surnames

0        TURNER
1      MARTINEZ
2          HALL
3          REED
4       SANCHEZ
         ...
526       YOUNG
527       BROWN
528         COX
529        GRAY
530     ROBERTS
Length: 531, dtype: object

In [30]:
owners = pd.DataFrame()

owners['CarNumber'] = unique_car_nums
owners['SURNAME'] = surnames
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
526  O136HO197RUS     YOUNG
527  O22097197RUS     BROWN
528  M0309X197RUS       COX
529  O673E8197RUS      GRAY
530  8610T8154RUS   ROBERTS

[531 rows x 2 columns]

In [31]:

new_df.loc[len(new_df)] = ['K555JG154RUS', 1, 7200.00, 'Toyota', 'Corolla', 2010]
new_df.loc[len(new_df)] = ['K444JG154RUS', 1, 200.00, 'LandRover', 'RangeRover', 2011]
new_df.loc[len(new_df)] = ['K333JG154RUS', 1, 700.00, 'Lexus', 'RX', 2013]
new_df.loc[len(new_df)] = ['K111JG154RUS', 1, 720.00, 'Lexus', 'LS', 2015]
new_df.loc[len(new_df)] = ['K222JG154RUS', 1, 72000.00, 'BMW', '5-series', 2011]

In [32]:
owners = owners[:len(owners) - 20]

In [33]:
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
506  T914CT197RUS      DIAZ
507  E41977152RUS     CLARK
508  9464EX178RUS     BAKER
509  O50197197RUS   ALVAREZ
510  7608EE777RUS      RUIZ

[511 rows x 2 columns]

In [34]:
new_rows = pd.DataFrame({
    'CarNumber': ['SJ0273Y61RUS', 'AP321E161RUS', 'CS527Y161RUS'],
    'SURNAME': ['RODGERS', 'JHONSONS', 'COOPERS']
})

owners = pd.concat([owners, new_rows], ignore_index=True)
owners

        CarNumber   SURNAME
0    Y163O8161RUS    TURNER
1     E432XX77RUS  MARTINEZ
2     7184TT36RUS      HALL
3    X582HE161RUS      REED
4    92918M178RUS   SANCHEZ
..            ...       ...
509  O50197197RUS   ALVAREZ
510  7608EE777RUS      RUIZ
511  SJ0273Y61RUS   RODGERS
512  AP321E161RUS  JHONSONS
513  CS527Y161RUS   COOPERS

[514 rows x 2 columns]

In [35]:
new_df.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
2   7184TT36RUS       1 2100.00    Ford  Focus  1984
3  X582HE161RUS       2 2000.00    Ford  Focus  2015
4  92918M178RUS       1 5700.00    Ford  Focus  2014

In [36]:
pd.merge(new_df, owners, on='CarNumber', how='inner')

        CarNumber  Refund   Fines        Make   Model  Year   SURNAME
0    Y163O8161RUS       2 3200.00        Ford   Focus  1989    TURNER
1     E432XX77RUS       1 6500.00      Toyota   Camry  1995  MARTINEZ
2     7184TT36RUS       1 2100.00        Ford   Focus  1984      HALL
3    X582HE161RUS       2 2000.00        Ford   Focus  2015      REED
4    92918M178RUS       1 5700.00        Ford   Focus  2014   SANCHEZ
..            ...     ...     ...         ...     ...   ...       ...
894  8182XX154RUS       1  200.00        Ford   Focus  1996  ANDERSON
895   X796TH96RUS       1  500.00        Ford   Focus  2002     ADAMS
896  T011MY163RUS       2 4000.00        Ford   Focus  1996    RIVERA
897   T341CC96RUS       2 1000.00  Volkswagen  Passat  2012     EVANS
898   T119CT96RUS       1 2000.00        Ford   Focus  1984    BAILEY

[899 rows x 7 columns]

In [37]:
pd.merge(new_df, owners, on='CarNumber', how='outer')

        CarNumber  Refund    Fines  Make  Model    Year   SURNAME
0    704687163RUS    2.00  1400.00  Ford  Focus 2014.00     ADAMS
1    704787163RUS    2.00  2800.00  Ford  Focus 2005.00    BROOKS
2    704987163RUS    2.00  8594.59  Ford  Focus 2014.00     JONES
3    705287163RUS    2.00  2000.00  Ford  Focus 1990.00  PHILLIPS
4    705387163RUS    2.00   700.00  Ford  Focus 2005.00    MURPHY
..            ...     ...      ...   ...    ...     ...       ...
928  Y973O8197RUS    2.00  8594.59  Ford  Focus 2005.00   JIMENEZ
929  Y973O8197RUS    1.00 34800.00  Ford  Focus 2013.00   JIMENEZ
930  Y973O8197RUS    1.00 69600.00  Ford  Focus 1989.00   JIMENEZ
931  Y973O8197RUS    1.00 34800.00  Ford  Focus 2009.00   JIMENEZ
932  Y973O8197RUS    2.00  8594.59  Ford  Focus 2014.00   JIMENEZ

[933 rows x 7 columns]

In [38]:
pd.merge(new_df, owners, on='CarNumber', how='left')

        CarNumber  Refund    Fines       Make       Model  Year   SURNAME
0    Y163O8161RUS       2  3200.00       Ford       Focus  1989    TURNER
1     E432XX77RUS       1  6500.00     Toyota       Camry  1995  MARTINEZ
2     7184TT36RUS       1  2100.00       Ford       Focus  1984      HALL
3    X582HE161RUS       2  2000.00       Ford       Focus  2015      REED
4    92918M178RUS       1  5700.00       Ford       Focus  2014   SANCHEZ
..            ...     ...      ...        ...         ...   ...       ...
925  K555JG154RUS       1  7200.00     Toyota     Corolla  2010       NaN
926  K444JG154RUS       1   200.00  LandRover  RangeRover  2011       NaN
927  K333JG154RUS       1   700.00      Lexus          RX  2013       NaN
928  K111JG154RUS       1   720.00      Lexus          LS  2015       NaN
929  K222JG154RUS       1 72000.00        BMW    5-series  2011       NaN

[930 rows x 7 columns]

In [39]:
pd.merge(new_df, owners, on='CarNumber', how='right')

        CarNumber  Refund    Fines    Make    Model    Year   SURNAME
0    Y163O8161RUS    2.00  3200.00    Ford    Focus 1989.00    TURNER
1    Y163O8161RUS    2.00  1600.00    Ford    Focus 1999.00    TURNER
2     E432XX77RUS    1.00  6500.00  Toyota    Camry 1995.00  MARTINEZ
3     E432XX77RUS    2.00 13000.00  Toyota    Camry 1992.00  MARTINEZ
4     7184TT36RUS    1.00  2100.00    Ford    Focus 1984.00      HALL
..            ...     ...      ...     ...      ...     ...       ...
897  7608EE777RUS    1.00  4000.00   Skoda  Octavia 2013.00      RUIZ
898  7608EE777RUS    1.00  4000.00   Skoda  Octavia 1987.00      RUIZ
899  SJ0273Y61RUS     NaN      NaN     NaN      NaN     NaN   RODGERS
900  AP321E161RUS     NaN      NaN     NaN      NaN     NaN  JHONSONS
901  CS527Y161RUS     NaN      NaN     NaN      NaN     NaN   COOPERS

[902 rows x 7 columns]

In [40]:
pd.pivot_table(new_df, values='Fines', index=['Make', 'Model'], columns='Year', aggfunc='sum')

Year                      1980      1981      1982      1983      1984  \
Make       Model
BMW        5-series        NaN       NaN       NaN       NaN       NaN
Ford       Focus      89194.59 266783.76 107283.76 147289.17 106000.00
           Mondeo          NaN       NaN  46200.00       NaN       NaN
LandRover  RangeRover      NaN       NaN       NaN       NaN       NaN
Lexus      LS              NaN       NaN       NaN       NaN       NaN
           RX              NaN       NaN       NaN       NaN       NaN
Skoda      Octavia    13794.59   1900.00   8894.59       NaN   1300.00
Toyota     Camry      12000.00       NaN   1000.00   8594.59   1000.00
           Corolla         NaN   6800.00       NaN  12800.00       NaN
Volkswagen Golf       20800.00   8594.59   5000.00    200.00       NaN
           Jetta           NaN   1000.00       NaN       NaN       NaN
           Passat       900.00  12500.00       NaN   1100.00   8594.59
           Touareg         NaN       NaN       NaN       NaN       NaN

Year                       1985     1986     1987     1988      1989  ...  \
Make       Model                                                      ...
BMW        5-series         NaN      NaN      NaN      NaN       NaN  ...
Ford       Focus      307494.59 69700.00 98189.17 69667.52 200889.17  ...
           Mondeo           NaN      NaN      NaN      NaN       NaN  ...
LandRover  RangeRover       NaN      NaN      NaN      NaN       NaN  ...
Lexus      LS               NaN      NaN      NaN      NaN       NaN  ...
           RX               NaN      NaN      NaN      NaN       NaN  ...
Skoda      Octavia    153594.59      NaN  6000.00  5100.00   8594.59  ...
Toyota     Camry            NaN 19800.00      NaN      NaN    800.00  ...
           Corolla      4400.00      NaN 54300.00      NaN   7800.00  ...
Volkswagen Golf       168000.00      NaN   300.00      NaN    300.00  ...
           Jetta        9000.00      NaN      NaN 46000.00   4000.00  ...
           Passat           NaN 16000.00  2000.00  8594.59       NaN  ...
           Touareg          NaN      NaN      NaN      NaN       NaN  ...

Year                       2009     2010      2011      2012      2013  \
Make       Model
BMW        5-series         NaN      NaN  72000.00       NaN       NaN
Ford       Focus      159894.59 96000.00 117194.59 152989.17 297378.35
           Mondeo           NaN      NaN       NaN       NaN  41100.00
LandRover  RangeRover       NaN      NaN    200.00       NaN       NaN
Lexus      LS               NaN      NaN       NaN       NaN       NaN
           RX               NaN      NaN       NaN       NaN    700.00
Skoda      Octavia          NaN  3000.00   3000.00   1700.00  11800.00
Toyota     Camry            NaN 22400.00       NaN   7500.00       NaN
           Corolla      8594.59 13200.00   3400.00       NaN       NaN
Volkswagen Golf             NaN      NaN       NaN       NaN       NaN
           Jetta            NaN      NaN       NaN       NaN       NaN
           Passat       3200.00  9500.00       NaN   1000.00   1600.00
           Touareg      5800.00      NaN       NaN       NaN       NaN

Year                      2014      2015      2016      2017      2018
Make       Model
BMW        5-series        NaN       NaN       NaN       NaN       NaN
Ford       Focus      90378.35 172700.00 110789.17 114089.17 107800.00
           Mondeo          NaN       NaN       NaN   8600.00       NaN
LandRover  RangeRover      NaN       NaN       NaN       NaN       NaN
Lexus      LS              NaN    720.00       NaN       NaN       NaN
           RX              NaN       NaN       NaN       NaN       NaN
Skoda      Octavia    18900.00  16394.59  35700.00   2400.00 153200.00
Toyota     Camry           NaN       NaN    800.00       NaN       NaN
           Corolla         NaN  30300.00       NaN   6900.00       NaN
Volkswagen Golf       13900.00   4600.00       NaN       NaN   1000.00
           Jetta           NaN       NaN       NaN       NaN       NaN
           Passat     15000.00       NaN       NaN       NaN       NaN
           Touareg         NaN       NaN       NaN       NaN       NaN

[13 rows x 39 columns]

In [41]:
new_df.to_csv('fines.csv', index=None)
owners.to_csv('owners.csv', index=None)