In [19]:
import pandas as pd
df = pd.read_json('../data/auto.json')
df = df.set_index('CarNumber')

In [20]:
df

              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS       2  3200.00    Ford    Focus
E432XX77RUS        1  6500.00  Toyota    Camry
7184TT36RUS        1  2100.00    Ford    Focus
X582HE161RUS       2  2000.00    Ford    Focus
92918M178RUS       1  5700.00    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS       2  1600.00    Ford    Focus
M0309X197RUS       1 22300.00    Ford    Focus
O673E8197RUS       2   600.00    Ford    Focus
8610T8154RUS       1  2000.00    Ford    Focus
H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 4 columns]

In [21]:
pd.set_option('display.float_format', '{:.2f}'.format)
df[df['Fines'] > 2100]

              Refund    Fines        Make    Model
CarNumber
Y163O8161RUS       2  3200.00        Ford    Focus
E432XX77RUS        1  6500.00      Toyota    Camry
92918M178RUS       1  5700.00        Ford    Focus
H234YH197RUS       2  6000.00        Ford    Focus
E40577152RUS       1  8594.59        Ford    Focus
...              ...      ...         ...      ...
O718MM163RUS       2  8594.59        Ford    Focus
7065C8197RUS       2 11400.00  Volkswagen   Passat
O22097197RUS       1 24300.00        Ford    Focus
M0309X197RUS       1 22300.00        Ford    Focus
H419XE197RUS       2  8594.59      Toyota  Corolla

[455 rows x 4 columns]

In [22]:
df[(df['Fines'] > 2100) & (df['Refund'] == 2)]

              Refund    Fines        Make    Model
CarNumber
Y163O8161RUS       2  3200.00        Ford    Focus
H234YH197RUS       2  6000.00        Ford    Focus
707987163RUS       2  2200.00        Ford    Focus
K330T8197RUS       2  8200.00       Skoda  Octavia
M592CH197RUS       2  8594.59       Skoda  Octavia
...              ...      ...         ...      ...
O136HO197RUS       2  7800.00      Toyota  Corolla
O68897197RUS       2 12300.00        Ford    Focus
O718MM163RUS       2  8594.59        Ford    Focus
7065C8197RUS       2 11400.00  Volkswagen   Passat
H419XE197RUS       2  8594.59      Toyota  Corolla

[309 rows x 4 columns]

In [23]:
df[df['Model'].isin(['Focus', 'Corolla'])]

              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS       2  3200.00    Ford    Focus
7184TT36RUS        1  2100.00    Ford    Focus
X582HE161RUS       2  2000.00    Ford    Focus
92918M178RUS       1  5700.00    Ford    Focus
H234YH197RUS       2  6000.00    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS       2  1600.00    Ford    Focus
M0309X197RUS       1 22300.00    Ford    Focus
O673E8197RUS       2   600.00    Ford    Focus
8610T8154RUS       1  2000.00    Ford    Focus
H419XE197RUS       2  8594.59  Toyota  Corolla

[593 rows x 4 columns]

In [24]:
df[df.index.isin(['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS'])]

              Refund     Fines  Make  Model
CarNumber
92928M178RUS       1   8594.59  Ford  Focus
H115YO163RUS       1   2200.00  Ford  Focus
7788KT197RUS       2  12000.00  Ford  Focus
X758HY197RUS       2  24200.00  Ford  Focus
X758HY197RUS       2  72600.00  Ford  Focus
Y7689C197RUS       1  27000.00  Ford  Focus
92928M178RUS       1    600.00  Ford  Focus
H115YO163RUS       1   8594.59  Ford  Focus
H115YO163RUS       2   1100.00  Ford  Focus
7788KT197RUS       2   8594.59  Ford  Focus
7788KT197RUS       1  20000.00  Ford  Focus
X758HY197RUS       2 145200.00  Ford  Focus
92928M178RUS       1   1200.00  Ford  Focus
Y7689C197RUS       2   9000.00  Ford  Focus
Y7689C197RUS       2  45000.00  Ford  Focus
7788KT197RUS       2   4000.00  Ford  Focus
Y7689C197RUS       1  36000.00  Ford  Focus
92928M178RUS       2   3000.00  Ford  Focus

In [25]:
group = df.groupby('Make')
group['Fines'].mean()

Make
Audi          4200.00
BMW           6031.53
Ford          8270.67
Skoda        10586.71
Toyota        9478.93
Volkswagen    9929.97
Volvo         8500.00
Name: Fines, dtype: float64

In [26]:
group = df.groupby(['Make', 'Model'])
group['Fines'].mean()

Make        Model
Ford        Focus      8184.45
            Mondeo    16533.33
Skoda       Octavia   10586.71
Toyota      Camry      8236.82
            Corolla   10583.03
Volkswagen  Golf      15744.73
            Jetta     10350.00
            Passat     6363.14
            Touareg    4498.92
Name: Fines, dtype: float64

In [27]:
group = df.groupby(['Make', 'Model'])
group['Fines'].count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

In [28]:
group = df.groupby(['Make', 'Model'])
group['Fines'].min()

Make        Model
Ford        Focus      100.00
            Mondeo    1100.00
Skoda       Octavia    300.00
Toyota      Camry      500.00
            Corolla    900.00
Volkswagen  Golf       200.00
            Jetta      500.00
            Passat     100.00
            Touareg    500.00
Name: Fines, dtype: float64

In [29]:
group = df.groupby(['Make', 'Model'])
group['Fines'].max()

Make        Model
Ford        Focus     180000.00
            Mondeo     46200.00
Skoda       Octavia   145000.00
Toyota      Camry      22400.00
            Corolla    34300.00
Volkswagen  Golf      168000.00
            Jetta      46000.00
            Passat     29700.00
            Touareg     8594.59
Name: Fines, dtype: float64

In [30]:
group = df.groupby(['Make', 'Model'])
group['Fines'].std()

Make        Model
Ford        Focus     15041.27
            Mondeo    18987.33
Skoda       Octavia   24339.74
Toyota      Camry      6410.25
            Corolla    9629.33
Volkswagen  Golf      36950.84
            Jetta     17743.03
            Passat     6969.74
            Touareg    3461.78
Name: Fines, dtype: float64

In [31]:
df.groupby('CarNumber')['Fines'].size().sort_values(ascending=False)

CarNumber
Y7689C197RUS    4
7788KT197RUS    4
92928M178RUS    4
Y7129Y50RUS     3
X758HY197RUS    3
               ..
Y967O8197RUS    1
Y965O8197RUS    1
Y965EE197RUS    1
Y964O8197RUS    1
Y964EE197RUS    1
Name: Fines, Length: 531, dtype: int64

In [32]:
new_df = pd.read_json('../data/auto.json')
new_df[new_df['CarNumber'] == 'Y7689C197RUS']

        CarNumber  Refund    Fines  Make  Model
183  Y7689C197RUS       1 27000.00  Ford  Focus
531  Y7689C197RUS       2  9000.00  Ford  Focus
554  Y7689C197RUS       2 45000.00  Ford  Focus
665  Y7689C197RUS       1 36000.00  Ford  Focus

In [33]:
df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False)

CarNumber
X758HY197RUS   242000.00
9020YC197RUS   217500.00
M0279X197RUS   216000.00
Y352O8197RUS   207200.00
Y778EE197RUS   192000.00
                  ...
Y166O8161RUS      100.00
K326T8197RUS      100.00
Y195O8161RUS      100.00
C58078163RUS      100.00
705787163RUS      100.00
Name: Fines, Length: 531, dtype: float64

In [34]:
new_df[new_df['CarNumber'] == 'X758HY197RUS']

        CarNumber  Refund     Fines  Make  Model
98   X758HY197RUS       2  24200.00  Ford  Focus
158  X758HY197RUS       2  72600.00  Ford  Focus
401  X758HY197RUS       2 145200.00  Ford  Focus

In [35]:
group = df.groupby('CarNumber')['Model'].nunique()
group[group > 1]

Series([], Name: Model, dtype: int64)